# Generated by Django 3.2 on 2021-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='nah', max_length=200),
            preserve_default=False,
        ),
    ]
